avatar:
  medium: "300x300>"
  thumb: "100x100>"
  mini: "48x48>"
  default_url: "/images/:style/missing.png"
per_page:
  products: 6
precision: 0
image:
  medium: "220x220>"
  thumb: "100x100>"
  mini: "48x48>"
  default_url: "/images/:style/missing.png"
index:
  id: 1
